package com.candra.chillivision.service

const val SUBSCRIPTION_MAX_USAGE_AI_FREE = 0;
const val SUBSCRIPTION_MAX_USAGE_AI_REGULAR = 10;
const val SUBSCRIPTION_MAX_USAGE_AI_PREMIUM = 100;

const val SUBSCRIPTION_MAX_USAGE_DETECT_FREE = 5;
const val SUBSCRIPTION_MAX_USAGE_DETECT_REGULAR = 100;
const val SUBSCRIPTION_MAX_USAGE_DETECT_PREMIUM = 500;

const val MAX_SAVE_HISTORY_FREE = 0;
const val MAX_SAVE_HISTORY_REGULAR = 50;
const val MAX_SAVE_HISTORY_PREMIUM = 200;